<?php

namespace App;

use App\Helpers\Roles\Gate;
use App\Models\Users\Role;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Arr;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens;


    const USER_ACTIVE    = 1;
    const USER_NO_ACTIVE = 0;

    const USER_VERIFIED    = 1;
    const USER_NO_VERIFIED = 0;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'verified'          => 'boolean',
        'permissions'       => 'array'
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function __call($method, $parameters)
    {
        $methods = ['hasAccess'];

        if (in_array($method, $methods)) {
            $gate = new Gate();
            return $gate->allow($this, Arr::first($parameters));
        }

        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
